import 'dart:async';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';

import '../../../../app/theme/shellvibe_tokens.dart';
import '../../../../app/widgets/shellvibe_ui.dart';
import '../../../../core/network/device_link/device_link_server.dart';
import '../../../../core/utils/platform_capabilities.dart';

/// Shows the short-lived, one-time QR payload generated by the desktop.
///
/// The server and its identity are owned by the caller. This keeps this view
/// safe to use before Phase 5 persistence exists: the screen renders only the
/// payload it was explicitly given and never stores its token or secret.
final class DeviceLinkPairingQrScreen extends StatefulWidget {
  final DeviceLinkQrPayload payload;
  final VoidCallback? onCancel;
  final Stream<void>? pairingEvents;
  final VoidCallback? onPaired;

  const DeviceLinkPairingQrScreen({
    super.key,
    required this.payload,
    this.onCancel,
    this.pairingEvents,
    this.onPaired,
  });

  @override
  State<DeviceLinkPairingQrScreen> createState() =>
      _DeviceLinkPairingQrScreenState();
}

class _DeviceLinkPairingQrScreenState extends State<DeviceLinkPairingQrScreen> {
  Timer? _timer;
  StreamSubscription<void>? _pairingSubscription;
  late int _remainingSeconds;

  @override
  void initState() {
    super.initState();
    _remainingSeconds = _secondsUntil(widget.payload.expiresAt);
    _timer = Timer.periodic(const Duration(seconds: 1), (_) => _tick());
    _listenForPairing();
  }

  @override
  void didUpdateWidget(covariant DeviceLinkPairingQrScreen oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.payload.expiresAt != widget.payload.expiresAt) {
      _remainingSeconds = _secondsUntil(widget.payload.expiresAt);
    }
    if (oldWidget.pairingEvents != widget.pairingEvents) {
      _listenForPairing();
    }
  }

  @override
  void dispose() {
    _timer?.cancel();
    unawaited(_pairingSubscription?.cancel());
    super.dispose();
  }

  void _listenForPairing() {
    unawaited(_pairingSubscription?.cancel());
    final events = widget.pairingEvents;
    if (events == null) {
      _pairingSubscription = null;
      return;
    }
    _pairingSubscription = events.listen((_) {
      if (!mounted) return;
      if (widget.onPaired != null) {
        widget.onPaired!();
      } else {
        Navigator.of(context).maybePop();
      }
    });
  }

  static int _secondsUntil(DateTime expiry) {
    final milliseconds = expiry
        .toUtc()
        .difference(DateTime.now().toUtc())
        .inMilliseconds;
    if (milliseconds <= 0) return 0;
    return (milliseconds + 999) ~/ 1000;
  }

  void _tick() {
    if (!mounted) return;
    final next = _secondsUntil(widget.payload.expiresAt);
    if (next == _remainingSeconds) return;
    setState(() => _remainingSeconds = next);
    if (next == 0) _timer?.cancel();
  }

  void _cancel() {
    widget.onCancel?.call();
    if (widget.onCancel == null && mounted) {
      Navigator.of(context).maybePop();
    }
  }

  @override
  Widget build(BuildContext context) {
    if (isMobilePlatform) {
      return Scaffold(
        appBar: AppBar(title: const Text('Device Link')),
        body: const Center(
          child: Padding(
            padding: EdgeInsets.all(24),
            child: Text(
              'The pairing QR code must be displayed on the desktop running ShellVibe.',
              textAlign: TextAlign.center,
            ),
          ),
        ),
      );
    }

    final expired = _remainingSeconds == 0;
    final theme = Theme.of(context);
    final tokens = ShellVibeTokens.resolve(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Pair a device'),
        actions: [
          ShellVibeButton.secondary(
            key: const Key('device_link_qr_cancel'),
            label: 'Cancel',
            onPressed: _cancel,
          ),
        ],
      ),
      body: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 480),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(
                  expired ? Icons.timer_off_outlined : Icons.devices_outlined,
                  size: 36,
                  color: expired ? tokens.danger : tokens.brand,
                ),
                const SizedBox(height: 12),
                Text(
                  expired ? 'QR code expired' : 'Scan with your phone',
                  style: theme.textTheme.headlineSmall,
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 8),
                Text(
                  expired
                      ? 'Generate a new code to pair another device.'
                      : 'This code can be used once and expires in $_remainingSeconds seconds.',
                  textAlign: TextAlign.center,
                  style: theme.textTheme.bodyMedium?.copyWith(
                    color: tokens.textSecondary,
                  ),
                ),
                const SizedBox(height: 24),
                if (!expired)
                  DecoratedBox(
                    // Deliberately outside the token system: a QR code needs a
                    // white quiet zone to be read, and a scanner does not care
                    // which theme the phone is in.
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(12),
                      boxShadow: const [
                        BoxShadow(blurRadius: 18, color: Colors.black26),
                      ],
                    ),
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: QrImageView(
                        key: const Key('device_link_qr'),
                        data: widget.payload.encode(),
                        size: math.min(
                          MediaQuery.sizeOf(context).width - 96,
                          320,
                        ),
                        backgroundColor: Colors.white,
                      ),
                    ),
                  ),
                const SizedBox(height: 20),
                Text(
                  widget.payload.host,
                  key: const Key('device_link_qr_host'),
                  style: theme.textTheme.titleMedium,
                ),
                const SizedBox(height: 4),
                Text(
                  'TLS pinned · port ${widget.payload.port}',
                  style: theme.textTheme.bodySmall?.copyWith(
                    color: tokens.textMuted,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
