import 'package:flutter/material.dart';
import 'package:shadcn_ui/shadcn_ui.dart';
import '../../features/settings/domain/models/app_settings_model.dart';
import 'shellvibe_tokens.dart';

/// Single source of truth for application UI themes and color palettes.
///
/// Every [AppPalette] defines:
/// - [darkTokens]: Full [ShellVibeTokens] contract with matching surfaces, brand,
///   gradients, text, and semantic accents.
/// - [lightTokens]: Corresponding daylight [ShellVibeTokens] contract.
/// - [darkSecondary] & [lightSecondary]: Accent colors used for secondary highlights.
class AppPaletteDefinition {
  final ShellVibeTokens darkTokens;
  final ShellVibeTokens lightTokens;
  final Color darkSecondary;
  final Color lightSecondary;

  const AppPaletteDefinition({
    required this.darkTokens,
    required this.lightTokens,
    required this.darkSecondary,
    required this.lightSecondary,
  });

  static AppPaletteDefinition forPalette(AppPalette palette) {
    return _registry[palette] ?? _registry[AppPalette.dark]!;
  }

  static ShadColorScheme buildShadColorScheme(
    AppPalette palette, {
    required bool isDark,
  }) {
    final def = forPalette(palette);
    final tokens = isDark ? def.darkTokens : def.lightTokens;

    if (isDark) {
      return ShadSlateColorScheme.dark(
        background: tokens.canvas,
        foreground: tokens.textPrimary,
        card: tokens.surface,
        cardForeground: tokens.textPrimary,
        primary: tokens.brand,
        primaryForeground: tokens.brandInk,
        muted: tokens.surfaceLow,
        mutedForeground: tokens.textMuted,
        border: tokens.border,
        destructive: tokens.danger,
      );
    } else {
      return ShadSlateColorScheme.light(
        background: tokens.canvas,
        foreground: tokens.textPrimary,
        card: tokens.surface,
        cardForeground: tokens.textPrimary,
        primary: tokens.brand,
        primaryForeground: tokens.brandInk,
        muted: tokens.surfaceLow,
        mutedForeground: tokens.textMuted,
        border: tokens.border,
        destructive: tokens.danger,
      );
    }
  }

  static final Map<AppPalette, AppPaletteDefinition> _registry = {
    // 1. ShellVibe Graphite (Default Nocturne)
    AppPalette.dark: const AppPaletteDefinition(
      darkTokens: ShellVibeTokens.dark,
      lightTokens: ShellVibeTokens.light,
      darkSecondary: Color(0xFF8AB4F8),
      lightSecondary: Color(0xFF2563EB),
    ),

    // 2. ShellVibe OLED (True Black with emerald highlight)
    AppPalette.oled: AppPaletteDefinition(
      darkTokens: ShellVibeTokens.dark.copyWith(
        canvas: const Color(0xFF000000),
        canvasGlow: const Color(0xFF0D1611),
        surface: const Color(0xFF080A0D),
        surfaceLow: const Color(0xFF000000),
        surfaceRaised: const Color(0xFF11161C),
        railBg: const Color(0xFF050709),
        terminalChrome: const Color(0xFF080A0D),
        brand: const Color(0xFF00E676),
        brandBright: const Color(0xFF69F0AE),
        brandSoft: const Color(0xFFB9F6CA),
        brandInk: const Color(0xFF000000),
        brandGradientTop: const Color(0xFF33FF99),
        brandGradientBottom: const Color(0xFF00B359),
        info: const Color(0xFF18FFFF),
        border: const Color(0xFF1F1F1F),
      ),
      lightTokens: ShellVibeTokens.light.copyWith(
        brand: const Color(0xFF007A3F),
        brandBright: const Color(0xFF006434),
        brandSoft: const Color(0xFF00B359),
        brandGradientTop: const Color(0xFF00A355),
        brandGradientBottom: const Color(0xFF006434),
        info: const Color(0xFF00838F),
      ),
      darkSecondary: const Color(0xFF18FFFF),
      lightSecondary: const Color(0xFF00838F),
    ),

    // 3. ShellVibe Teal (the brand palette: cool neutral ground, teal accent)
    //
    // Three colours were fixed by the brand work — the light ground #F6F7F8,
    // the night ground #0E1216 and the teal accent #0B6E6E — and the rest of
    // the contract is derived from them. The neutrals are the same cool blue
    // grey at every step rather than the violet-leaning greys Graphite uses,
    // so the teal is the only hue with any saturation on screen.
    //
    // The accent splits by mode. #0B6E6E is dark enough to carry white at
    // 6.1:1 on daylight, but on the night ground it reads as a smudge rather
    // than an accent, so the dark side takes a lightened sibling of the same
    // hue and flips the ink to near-black.
    AppPalette.teal: AppPaletteDefinition(
      darkTokens: ShellVibeTokens.dark.copyWith(
        canvas: const Color(0xFF0E1216),
        canvasGlow: const Color(0xFF161D22),
        surface: const Color(0xFF151A1F),
        surfaceLow: const Color(0xFF0A0E11),
        surfaceRaised: const Color(0xFF1C2329),
        terminalBg: const Color(0xFF0B0F12),
        terminalChrome: const Color(0xFF151A1F),
        railBg: const Color(0xFF12171B),
        border: const Color(0x12FFFFFF),
        textPrimary: const Color(0xFFE8EDF0),
        textSecondary: const Color(0xFFC7D0D6),
        textMuted: const Color(0xFF8A97A0),
        textSubtle: const Color(0xFF616D76),
        brand: const Color(0xFF2FB8B0),
        brandBright: const Color(0xFF5AD3CB),
        brandSoft: const Color(0xFFA7E8E3),
        brandInk: const Color(0xFF04100F),
        brandGradientTop: const Color(0xFF3FC4BB),
        brandGradientBottom: const Color(0xFF1C8F89),
        info: const Color(0xFF6FB2E8),
        success: const Color(0xFF5FC39B),
        warning: const Color(0xFFDBB56B),
        danger: const Color(0xFFEE8494),
        dangerMutedSurface: const Color(0xFF2A0F14),
        dangerMutedText: const Color(0xFFFFC4CC),
        dangerMutedBorder: const Color(0xFFB98A92),
      ),
      lightTokens: ShellVibeTokens.light.copyWith(
        canvas: const Color(0xFFF6F7F8),
        surfaceLow: const Color(0xFFEDEFF1),
        terminalBg: const Color(0xFFF6F7F8),
        terminalChrome: const Color(0xFFE7EAEC),
        border: const Color(0x140E1216),
        textPrimary: const Color(0xFF12171B),
        textSecondary: const Color(0xFF333B42),
        textMuted: const Color(0xFF5E6A73),
        textSubtle: const Color(0xFF828C94),
        brand: const Color(0xFF0B6E6E),
        brandBright: const Color(0xFF075757),
        brandSoft: const Color(0xFF0E8A8A),
        brandGradientTop: const Color(0xFF0E8A8A),
        brandGradientBottom: const Color(0xFF085C5C),
        info: const Color(0xFF1D6FD0),
        success: const Color(0xFF11705A),
        warning: const Color(0xFFA65A07),
        shadowColor: const Color(0x140E1216),
        shadowColorStrong: const Color(0x240E1216),
      ),
      darkSecondary: const Color(0xFF6FB2E8),
      lightSecondary: const Color(0xFF1D6FD0),
    ),

    // 3. Catppuccin (Mocha / Latte)
    AppPalette.catppuccin: AppPaletteDefinition(
      darkTokens: ShellVibeTokens.dark.copyWith(
        canvas: const Color(0xFF1E1E2E),
        canvasGlow: const Color(0xFF313244),
        surface: const Color(0xFF181825),
        surfaceLow: const Color(0xFF11111B),
        surfaceRaised: const Color(0xFF24273A),
        railBg: const Color(0xFF181825),
        terminalChrome: const Color(0xFF181825),
        brand: const Color(0xFF89B4FA),
        brandBright: const Color(0xFFB4BEFE),
        brandSoft: const Color(0xFFCBA6F7),
        brandInk: const Color(0xFF11111B),
        brandGradientTop: const Color(0xFFB4BEFE),
        brandGradientBottom: const Color(0xFF74C7EC),
        textPrimary: const Color(0xFFCDD6F4),
        textSecondary: const Color(0xFFBAC2DE),
        textMuted: const Color(0xFFA6ADC8),
        textSubtle: const Color(0xFF6C7086),
        border: const Color(0xFF313244),
        info: const Color(0xFF89DCEB),
        success: const Color(0xFFA6E3A1),
        warning: const Color(0xFFF9E2AF),
        danger: const Color(0xFFF38BA8),
      ),
      lightTokens: ShellVibeTokens.light.copyWith(
        canvas: const Color(0xFFEFF1F5),
        canvasGlow: const Color(0xFFFFFFFF),
        surface: const Color(0xFFE6E9EF),
        surfaceLow: const Color(0xFFDCE0E8),
        surfaceRaised: const Color(0xFFFFFFFF),
        railBg: const Color(0xFFE6E9EF),
        terminalBg: const Color(0xFFEFF1F5),
        terminalChrome: const Color(0xFFE6E9EF),
        brand: const Color(0xFF1E66F5),
        brandBright: const Color(0xFF04A5E5),
        brandSoft: const Color(0xFF7287FD),
        brandInk: const Color(0xFFFFFFFF),
        brandGradientTop: const Color(0xFF7287FD),
        brandGradientBottom: const Color(0xFF1E66F5),
        textPrimary: const Color(0xFF4C4F69),
        textSecondary: const Color(0xFF5C5F77),
        textMuted: const Color(0xFF63667B),
        textSubtle: const Color(0xFF7C8196),
        border: const Color(0xFFBCC0CC),
        info: const Color(0xFF04A5E5),
        success: const Color(0xFF40A02B),
        warning: const Color(0xFFDF8E1D),
        danger: const Color(0xFFE64553),
      ),
      darkSecondary: const Color(0xFFCBA6F7),
      lightSecondary: const Color(0xFF8839EF),
    ),

    // 4. Nord (Polar Night / Snow Storm)
    AppPalette.nord: AppPaletteDefinition(
      darkTokens: ShellVibeTokens.dark.copyWith(
        canvas: const Color(0xFF2E3440),
        canvasGlow: const Color(0xFF434C5E),
        surface: const Color(0xFF3B4252),
        surfaceLow: const Color(0xFF242933),
        surfaceRaised: const Color(0xFF434C5E),
        railBg: const Color(0xFF2E3440),
        terminalChrome: const Color(0xFF3B4252),
        brand: const Color(0xFF88C0D0),
        brandBright: const Color(0xFF8FBCBB),
        brandSoft: const Color(0xFF81A1C1),
        brandInk: const Color(0xFF2E3440),
        brandGradientTop: const Color(0xFF8FBCBB),
        brandGradientBottom: const Color(0xFF81A1C1),
        textPrimary: const Color(0xFFECEFF4),
        textSecondary: const Color(0xFFE5E9F0),
        textMuted: const Color(0xFFD8DEE9),
        textSubtle: const Color(0xFF8793AB),
        border: const Color(0xFF4C566A),
        info: const Color(0xFF5E81AC),
        success: const Color(0xFFA3BE8C),
        warning: const Color(0xFFEBCB8B),
        danger: const Color(0xFFBF616A),
      ),
      lightTokens: ShellVibeTokens.light.copyWith(
        canvas: const Color(0xFFECEFF4),
        canvasGlow: const Color(0xFFFFFFFF),
        surface: const Color(0xFFE5E9F0),
        surfaceLow: const Color(0xFFD8DEE9),
        surfaceRaised: const Color(0xFFFFFFFF),
        railBg: const Color(0xFFE5E9F0),
        terminalBg: const Color(0xFFECEFF4),
        terminalChrome: const Color(0xFFE5E9F0),
        brand: const Color(0xFF50719A),
        brandBright: const Color(0xFF81A1C1),
        brandSoft: const Color(0xFF88C0D0),
        brandInk: const Color(0xFFFFFFFF),
        brandGradientTop: const Color(0xFF6E93B6),
        brandGradientBottom: const Color(0xFF4C566A),
        textPrimary: const Color(0xFF2E3440),
        textSecondary: const Color(0xFF3B4252),
        textMuted: const Color(0xFF434C5E),
        textSubtle: const Color(0xFF737F99),
        border: const Color(0xFFD8DEE9),
        info: const Color(0xFF88C0D0),
        success: const Color(0xFFA3BE8C),
        warning: const Color(0xFFD08770),
        danger: const Color(0xFFBF616A),
      ),
      darkSecondary: const Color(0xFF81A1C1),
      lightSecondary: const Color(0xFF88C0D0),
    ),

    // 5. Dracula
    AppPalette.dracula: AppPaletteDefinition(
      darkTokens: ShellVibeTokens.dark.copyWith(
        canvas: const Color(0xFF282A36),
        canvasGlow: const Color(0xFF44475A),
        surface: const Color(0xFF343746),
        surfaceLow: const Color(0xFF21222C),
        surfaceRaised: const Color(0xFF44475A),
        railBg: const Color(0xFF282A36),
        terminalChrome: const Color(0xFF343746),
        brand: const Color(0xFFBD93F9),
        brandBright: const Color(0xFFCAA9FA),
        brandSoft: const Color(0xFFFF79C6),
        brandInk: const Color(0xFF282A36),
        brandGradientTop: const Color(0xFFCAA9FA),
        brandGradientBottom: const Color(0xFF9A6BD8),
        textPrimary: const Color(0xFFF8F8F2),
        textSecondary: const Color(0xFFE2E2DC),
        textMuted: const Color(0xFFA3A3A3),
        textSubtle: const Color(0xFF7684B2),
        border: const Color(0xFF44475A),
        info: const Color(0xFF8BE9FD),
        success: const Color(0xFF50FA7B),
        warning: const Color(0xFFF1FA8C),
        danger: const Color(0xFFFF5555),
      ),
      lightTokens: ShellVibeTokens.light.copyWith(
        canvas: const Color(0xFFF8F8F2),
        canvasGlow: const Color(0xFFFFFFFF),
        surface: const Color(0xFFFFFFFF),
        surfaceLow: const Color(0xFFEAEAEA),
        surfaceRaised: const Color(0xFFF1F1EB),
        railBg: const Color(0xFFFFFFFF),
        terminalBg: const Color(0xFFF8F8F2),
        terminalChrome: const Color(0xFFFFFFFF),
        brand: const Color(0xFF7B52C7),
        brandBright: const Color(0xFF6236B8),
        brandSoft: const Color(0xFFBD93F9),
        brandInk: const Color(0xFFFFFFFF),
        brandGradientTop: const Color(0xFF9A6BD8),
        brandGradientBottom: const Color(0xFF6236B8),
        textPrimary: const Color(0xFF282A36),
        textSecondary: const Color(0xFF44475A),
        textMuted: const Color(0xFF6272A4),
        textSubtle: const Color(0xFF8F8F8F),
        border: const Color(0xFFD8D8D2),
        info: const Color(0xFF01A0E4),
        success: const Color(0xFF28A745),
        warning: const Color(0xFFC68A00),
        danger: const Color(0xFFE03131),
      ),
      darkSecondary: const Color(0xFFFF79C6),
      lightSecondary: const Color(0xFFE02475),
    ),

    // 6. Solarized (Dark / Light)
    AppPalette.solarizedDark: AppPaletteDefinition(
      darkTokens: ShellVibeTokens.dark.copyWith(
        canvas: const Color(0xFF002B36),
        canvasGlow: const Color(0xFF073642),
        surface: const Color(0xFF073642),
        surfaceLow: const Color(0xFF001F27),
        surfaceRaised: const Color(0xFF586E75),
        railBg: const Color(0xFF002B36),
        terminalChrome: const Color(0xFF073642),
        brand: const Color(0xFF2AA198),
        brandBright: const Color(0xFF38BFB5),
        brandSoft: const Color(0xFF268BD2),
        brandInk: const Color(0xFF002B36),
        brandGradientTop: const Color(0xFF38BFB5),
        brandGradientBottom: const Color(0xFF20857D),
        textPrimary: const Color(0xFF93A1A1),
        textSecondary: const Color(0xFF93A1A1),
        textMuted: const Color(0xFF8B9FA6),
        textSubtle: const Color(0xFF6B8489),
        border: const Color(0xFF586E75),
        info: const Color(0xFF268BD2),
        success: const Color(0xFF859900),
        warning: const Color(0xFFB58900),
        danger: const Color(0xFFDC322F),
      ),
      lightTokens: ShellVibeTokens.light.copyWith(
        canvas: const Color(0xFFFDF6E3),
        canvasGlow: const Color(0xFFFFFFFF),
        surface: const Color(0xFFEEE8D5),
        surfaceLow: const Color(0xFFE4DCBA),
        surfaceRaised: const Color(0xFFFFFFFF),
        railBg: const Color(0xFFEEE8D5),
        terminalBg: const Color(0xFFFDF6E3),
        terminalChrome: const Color(0xFFEEE8D5),
        brand: const Color(0xFF1E73AF),
        brandBright: const Color(0xFF1A6094),
        brandSoft: const Color(0xFF2AA198),
        brandInk: const Color(0xFFFFFFFF),
        brandGradientTop: const Color(0xFF2F8ACF),
        brandGradientBottom: const Color(0xFF175C8C),
        textPrimary: const Color(0xFF073642),
        textSecondary: const Color(0xFF4E6268),
        textMuted: const Color(0xFF51666C),
        textSubtle: const Color(0xFF728485),
        border: const Color(0xFFD5CCAC),
        info: const Color(0xFF2AA198),
        success: const Color(0xFF859900),
        warning: const Color(0xFFB58900),
        danger: const Color(0xFFDC322F),
      ),
      darkSecondary: const Color(0xFF268BD2),
      lightSecondary: const Color(0xFF2AA198),
    ),

    // 7. Tokyo Night (Night / Day)
    AppPalette.tokyoNight: AppPaletteDefinition(
      darkTokens: ShellVibeTokens.dark.copyWith(
        canvas: const Color(0xFF1A1B26),
        canvasGlow: const Color(0xFF24283B),
        surface: const Color(0xFF24283B),
        surfaceLow: const Color(0xFF16161E),
        surfaceRaised: const Color(0xFF414868),
        railBg: const Color(0xFF1A1B26),
        terminalChrome: const Color(0xFF24283B),
        brand: const Color(0xFF7AA2F7),
        brandBright: const Color(0xFF8DAEF8),
        brandSoft: const Color(0xFFBB9AF7),
        brandInk: const Color(0xFF1A1B26),
        brandGradientTop: const Color(0xFF8DAEF8),
        brandGradientBottom: const Color(0xFF6289EE),
        textPrimary: const Color(0xFFC0CAF5),
        textSecondary: const Color(0xFFA9B1D6),
        textMuted: const Color(0xFF9AA5CE),
        textSubtle: const Color(0xFF6C76A6),
        border: const Color(0xFF414868),
        info: const Color(0xFF7DCFFF),
        success: const Color(0xFF9ECE6A),
        warning: const Color(0xFFE0AF68),
        danger: const Color(0xFFF7768E),
      ),
      lightTokens: ShellVibeTokens.light.copyWith(
        canvas: const Color(0xFFE1E2E7),
        canvasGlow: const Color(0xFFFFFFFF),
        surface: const Color(0xFFD5D6DB),
        surfaceLow: const Color(0xFFCBCCD1),
        surfaceRaised: const Color(0xFFFFFFFF),
        railBg: const Color(0xFFD5D6DB),
        terminalBg: const Color(0xFFE1E2E7),
        terminalChrome: const Color(0xFFD5D6DB),
        brand: const Color(0xFF34548A),
        brandBright: const Color(0xFF263E66),
        brandSoft: const Color(0xFF7AA2F7),
        brandInk: const Color(0xFFFFFFFF),
        brandGradientTop: const Color(0xFF496EA8),
        brandGradientBottom: const Color(0xFF263E66),
        textPrimary: const Color(0xFF343B58),
        textSecondary: const Color(0xFF4C505E),
        textMuted: const Color(0xFF52586C),
        textSubtle: const Color(0xFF6F7383),
        border: const Color(0xFFC4C8D8),
        info: const Color(0xFF007197),
        success: const Color(0xFF485E30),
        warning: const Color(0xFF8C6C3E),
        danger: const Color(0xFF8C4351),
      ),
      darkSecondary: const Color(0xFFBB9AF7),
      lightSecondary: const Color(0xFF7AA2F7),
    ),

    // 8. Gruvbox (Dark / Light)
    AppPalette.gruvbox: AppPaletteDefinition(
      darkTokens: ShellVibeTokens.dark.copyWith(
        canvas: const Color(0xFF282828),
        canvasGlow: const Color(0xFF3C3836),
        surface: const Color(0xFF3C3836),
        surfaceLow: const Color(0xFF1D2021),
        surfaceRaised: const Color(0xFF504945),
        railBg: const Color(0xFF282828),
        terminalChrome: const Color(0xFF3C3836),
        brand: const Color(0xFFFE8019),
        brandBright: const Color(0xFFFFA347),
        brandSoft: const Color(0xFFFABD2F),
        brandInk: const Color(0xFF282828),
        brandGradientTop: const Color(0xFFFFA347),
        brandGradientBottom: const Color(0xFFD65D0E),
        textPrimary: const Color(0xFFEBDBB2),
        textSecondary: const Color(0xFFD5C4A1),
        textMuted: const Color(0xFFBDAE93),
        textSubtle: const Color(0xFF95867A),
        border: const Color(0xFF504945),
        info: const Color(0xFF83A598),
        success: const Color(0xFFB8BB26),
        warning: const Color(0xFFFABD2F),
        danger: const Color(0xFFFB4934),
      ),
      lightTokens: ShellVibeTokens.light.copyWith(
        canvas: const Color(0xFFFBF1C7),
        canvasGlow: const Color(0xFFFFFFFF),
        surface: const Color(0xFFEBDBB2),
        surfaceLow: const Color(0xFFD5C4A1),
        surfaceRaised: const Color(0xFFFFFFFF),
        railBg: const Color(0xFFEBDBB2),
        terminalBg: const Color(0xFFFBF1C7),
        terminalChrome: const Color(0xFFEBDBB2),
        brand: const Color(0xFFAF3A03),
        brandBright: const Color(0xFF9D0006),
        brandSoft: const Color(0xFFFE8019),
        brandInk: const Color(0xFFFFFFFF),
        brandGradientTop: const Color(0xFFD65D0E),
        brandGradientBottom: const Color(0xFF9D0006),
        textPrimary: const Color(0xFF3C3836),
        textSecondary: const Color(0xFF504945),
        textMuted: const Color(0xFF665C54),
        textSubtle: const Color(0xFF837567),
        border: const Color(0xFFD5C4A1),
        info: const Color(0xFF076678),
        success: const Color(0xFF79740E),
        warning: const Color(0xFFB57614),
        danger: const Color(0xFFCC241D),
      ),
      darkSecondary: const Color(0xFFFABD2F),
      lightSecondary: const Color(0xFFB57614),
    ),

    // 9. One Dark / One Light
    AppPalette.oneDark: AppPaletteDefinition(
      darkTokens: ShellVibeTokens.dark.copyWith(
        canvas: const Color(0xFF21252B),
        canvasGlow: const Color(0xFF282C34),
        surface: const Color(0xFF282C34),
        surfaceLow: const Color(0xFF1B1D23),
        surfaceRaised: const Color(0xFF3E4451),
        railBg: const Color(0xFF21252B),
        terminalChrome: const Color(0xFF282C34),
        brand: const Color(0xFF61AFEF),
        brandBright: const Color(0xFF78C0FF),
        brandSoft: const Color(0xFFC678DD),
        brandInk: const Color(0xFF21252B),
        brandGradientTop: const Color(0xFF78C0FF),
        brandGradientBottom: const Color(0xFF4894DF),
        textPrimary: const Color(0xFFABB2BF),
        textSecondary: const Color(0xFF9DA5B4),
        textMuted: const Color(0xFF9199A9),
        textSubtle: const Color(0xFF727A89),
        border: const Color(0xFF3E4451),
        info: const Color(0xFF56B6C2),
        success: const Color(0xFF98C379),
        warning: const Color(0xFFE5C07B),
        danger: const Color(0xFFE06C75),
      ),
      lightTokens: ShellVibeTokens.light.copyWith(
        canvas: const Color(0xFFFAFAFA),
        canvasGlow: const Color(0xFFFFFFFF),
        surface: const Color(0xFFF0F0F0),
        surfaceLow: const Color(0xFFE5E5E6),
        surfaceRaised: const Color(0xFFFFFFFF),
        railBg: const Color(0xFFF0F0F0),
        terminalBg: const Color(0xFFFAFAFA),
        terminalChrome: const Color(0xFFF0F0F0),
        brand: const Color(0xFF2B67EE),
        brandBright: const Color(0xFF2960D9),
        brandSoft: const Color(0xFF61AFEF),
        brandInk: const Color(0xFFFFFFFF),
        brandGradientTop: const Color(0xFF5C8DF5),
        brandGradientBottom: const Color(0xFF2960D9),
        textPrimary: const Color(0xFF383A42),
        textSecondary: const Color(0xFF4F525E),
        textMuted: const Color(0xFF696C77),
        textSubtle: const Color(0xFF83848B),
        border: const Color(0xFFD0D0D4),
        info: const Color(0xFF0184BC),
        success: const Color(0xFF50A14F),
        warning: const Color(0xFFC18401),
        danger: const Color(0xFFE45649),
      ),
      darkSecondary: const Color(0xFFC678DD),
      lightSecondary: const Color(0xFFA626A4),
    ),
  };
}
