// Terminal color scheme registry.
//
// Existing themes are transcribed from the original definitions in
// terminal_screen.dart; new themes are parsed from the
// mbadolato/iTerm2-Color-Schemes collection (.itermcolors).
// Regenerate the new entries with `python3 tool/gen_terminal_palettes.py`;
// the hex values in this file are the source of truth.
import 'package:flutter/material.dart';
import 'package:xterm2/xterm.dart';

import 'terminal_palette.dart';

/// A selectable terminal color scheme shown in Settings.
class TerminalPaletteData {
  const TerminalPaletteData({
    required this.palette,
    required this.label,
    required this.theme,
  });

  final TerminalPalette palette;
  final String label;
  final TerminalTheme theme;

  static TerminalPaletteData of(TerminalPalette palette) =>
      kTerminalPalettes.firstWhere((p) => p.palette == palette);

  static TerminalTheme themeOf(TerminalPalette palette) => of(palette).theme;
}

/// All selectable terminal color schemes, in Settings dropdown order:
/// the default (Dark Default) first, the rest sorted alphabetically by label.
const kTerminalPalettes = <TerminalPaletteData>[
    TerminalPaletteData(
      palette: TerminalPalette.dark,
      label: 'Dark Default',
      theme: TerminalTheme(
        cursor: Color(0xFFA855F7),
        selection: Color(0xFF3F3F46),
        foreground: Color(0xFFF4F4F5),
        background: Color(0xFF18181B),
        black: Color(0xFF27272A),
        red: Color(0xFFEF4444),
        green: Color(0xFF22C55E),
        yellow: Color(0xFFEAB308),
        blue: Color(0xFF3B82F6),
        magenta: Color(0xFFA855F7),
        cyan: Color(0xFF06B6D4),
        white: Color(0xFFE4E4E7),
        brightBlack: Color(0xFF52525B),
        brightRed: Color(0xFFF87171),
        brightGreen: Color(0xFF4ADE80),
        brightYellow: Color(0xFFFACC15),
        brightBlue: Color(0xFF60A5FA),
        brightMagenta: Color(0xFFC084FC),
        brightCyan: Color(0xFF22D3EE),
        brightWhite: Color(0xFFFAFAFA),
        searchHitBackground: Color(0xFF6366F1),
        searchHitBackgroundCurrent: Color(0xFFA855F7),
        searchHitForeground: Color(0xFFFFFFFF),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.ayuMirage,
      label: 'Ayu Mirage',
      theme: TerminalTheme(
        cursor: Color(0xFFFFCC66),
        selection: Color(0xFF409FFF),
        foreground: Color(0xFFCCCAC2),
        background: Color(0xFF1F2430),
                black: Color(0xFF171B24),
        red: Color(0xFFED8274),
        green: Color(0xFF87D96C),
        yellow: Color(0xFFFACC6E),
        blue: Color(0xFF6DCBFA),
        magenta: Color(0xFFDABAFA),
        cyan: Color(0xFF90E1C6),
        white: Color(0xFFC7C7C7),
        brightBlack: Color(0xFF686868),
        brightRed: Color(0xFFF28779),
        brightGreen: Color(0xFFD5FF80),
        brightYellow: Color(0xFFFFD173),
        brightBlue: Color(0xFF73D0FF),
        brightMagenta: Color(0xFFDFBFFF),
        brightCyan: Color(0xFF95E6CB),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF6DCBFA),
        searchHitBackgroundCurrent: Color(0xFFFACC6E),
        searchHitForeground: Color(0xFF1F2430),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.catppuccinLatte,
      label: 'Catppuccin Latte',
      theme: TerminalTheme(
        cursor: Color(0xFFDC8A78),
        selection: Color(0xFFDC8A78),
        foreground: Color(0xFF4C4F69),
        background: Color(0xFFEFF1F5),
                black: Color(0xFFBCC0CC),
        red: Color(0xFFD20F39),
        green: Color(0xFF40A02B),
        yellow: Color(0xFFDF8E1D),
        blue: Color(0xFF1E66F5),
        magenta: Color(0xFFEA76CB),
        cyan: Color(0xFF179299),
        white: Color(0xFF5C5F77),
        brightBlack: Color(0xFFACB0BE),
        brightRed: Color(0xFFE7103F),
        brightGreen: Color(0xFF46B02F),
        brightYellow: Color(0xFFE49931),
        brightBlue: Color(0xFF3878F6),
        brightMagenta: Color(0xFFEF95D7),
        brightCyan: Color(0xFF19A1A8),
        brightWhite: Color(0xFF6C6F85),
        searchHitBackground: Color(0xFF1E66F5),
        searchHitBackgroundCurrent: Color(0xFFDF8E1D),
        searchHitForeground: Color(0xFFEFF1F5),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.catppuccin,
      label: 'Catppuccin Macchiato',
      theme: TerminalTheme(
        cursor: Color(0xFFF4D9E1),
        selection: Color(0xFF5B6078),
        foreground: Color(0xFFCAD3F5),
        background: Color(0xFF24273A),
        black: Color(0xFF494D64),
        red: Color(0xFFED8796),
        green: Color(0xFFA6DA95),
        yellow: Color(0xFFEED49F),
        blue: Color(0xFF8AADF4),
        magenta: Color(0xFFF5BDE6),
        cyan: Color(0xFF8BD5CA),
        white: Color(0xFFB8C0E0),
        brightBlack: Color(0xFF5B6078),
        brightRed: Color(0xFFF2A7B2),
        brightGreen: Color(0xFFBDE3B0),
        brightYellow: Color(0xFFF4E3C1),
        brightBlue: Color(0xFFADC5F7),
        brightMagenta: Color(0xFFF493DA),
        brightCyan: Color(0xFFA5DED6),
        brightWhite: Color(0xFFA5ADCB),
        searchHitBackground: Color(0xFFF5E0DC),
        searchHitBackgroundCurrent: Color(0xFFF38BA8),
        searchHitForeground: Color(0xFF1E1E2E),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.catppuccinMocha,
      label: 'Catppuccin Mocha',
      theme: TerminalTheme(
        cursor: Color(0xFFF5E0DC),
        selection: Color(0xFFF5E0DC),
        foreground: Color(0xFFCDD6F4),
        background: Color(0xFF1E1E2E),
                black: Color(0xFF45475A),
        red: Color(0xFFF38BA8),
        green: Color(0xFFA6E3A1),
        yellow: Color(0xFFF9E2AF),
        blue: Color(0xFF89B4FA),
        magenta: Color(0xFFF5C2E7),
        cyan: Color(0xFF94E2D5),
        white: Color(0xFFBAC2DE),
        brightBlack: Color(0xFF585B70),
        brightRed: Color(0xFFF7AEC2),
        brightGreen: Color(0xFFC2ECBF),
        brightYellow: Color(0xFFFCD682),
        brightBlue: Color(0xFFAECCFC),
        brightMagenta: Color(0xFFF398DA),
        brightCyan: Color(0xFFB1EAE1),
        brightWhite: Color(0xFFA6ADC8),
        searchHitBackground: Color(0xFF89B4FA),
        searchHitBackgroundCurrent: Color(0xFFF9E2AF),
        searchHitForeground: Color(0xFF1E1E2E),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.cyberpunk,
      label: 'Cyberpunk',
      theme: TerminalTheme(
        cursor: Color(0xFF00FF9F),
        selection: Color(0xFF3A1C71),
        foreground: Color(0xFF00F0FF),
        background: Color(0xFF120E24),
        black: Color(0xFF100C1E),
        red: Color(0xFFFF0055),
        green: Color(0xFF00FF9F),
        yellow: Color(0xFFFFE600),
        blue: Color(0xFF00F0FF),
        magenta: Color(0xFFFF007F),
        cyan: Color(0xFF00FFFF),
        white: Color(0xFFFFFFFF),
        brightBlack: Color(0xFF4A3E6D),
        brightRed: Color(0xFFFF3377),
        brightGreen: Color(0xFF33FFAF),
        brightYellow: Color(0xFFFFEB33),
        brightBlue: Color(0xFF33F3FF),
        brightMagenta: Color(0xFFFF3399),
        brightCyan: Color(0xFF33FFFF),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF00FF9F),
        searchHitBackgroundCurrent: Color(0xFFFF007F),
        searchHitForeground: Color(0xFF120E24),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.doomOne,
      label: 'Doom One',
      theme: TerminalTheme(
        cursor: Color(0xFF51AFEF),
        selection: Color(0xFF42444B),
        foreground: Color(0xFFBBC2CF),
        background: Color(0xFF282C34),
                black: Color(0xFF000000),
        red: Color(0xFFFF6C6B),
        green: Color(0xFF98BE65),
        yellow: Color(0xFFECBE7B),
        blue: Color(0xFFA9A1E1),
        magenta: Color(0xFFC678DD),
        cyan: Color(0xFF51AFEF),
        white: Color(0xFFBBC2CF),
        brightBlack: Color(0xFF595959),
        brightRed: Color(0xFFFF6655),
        brightGreen: Color(0xFF99BB66),
        brightYellow: Color(0xFFECBE7B),
        brightBlue: Color(0xFFA9A1E1),
        brightMagenta: Color(0xFFC678DD),
        brightCyan: Color(0xFF51AFEF),
        brightWhite: Color(0xFFBFBFBF),
        searchHitBackground: Color(0xFFA9A1E1),
        searchHitBackgroundCurrent: Color(0xFFECBE7B),
        searchHitForeground: Color(0xFF282C34),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.dracula,
      label: 'Dracula',
      theme: TerminalTheme(
        cursor: Color(0xFFF8F8F2),
        selection: Color(0xFF44475A),
        foreground: Color(0xFFF8F8F2),
        background: Color(0xFF282A36),
        black: Color(0xFF21222C),
        red: Color(0xFFFF5555),
        green: Color(0xFF50FA7B),
        yellow: Color(0xFFF1FA8C),
        blue: Color(0xFFBD93F9),
        magenta: Color(0xFFFF79C6),
        cyan: Color(0xFF8BE9FD),
        white: Color(0xFFF8F8F2),
        brightBlack: Color(0xFF6272A4),
        brightRed: Color(0xFFFF6E6E),
        brightGreen: Color(0xFF69FF94),
        brightYellow: Color(0xFFFFFFA5),
        brightBlue: Color(0xFFD6ACFF),
        brightMagenta: Color(0xFFFF92D0),
        brightCyan: Color(0xFFA4FFFF),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFFBD93F9),
        searchHitBackgroundCurrent: Color(0xFFFF79C6),
        searchHitForeground: Color(0xFF282A36),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.everforestDark,
      label: 'Everforest Dark',
      theme: TerminalTheme(
        cursor: Color(0xFFE69875),
        selection: Color(0xFF543A48),
        foreground: Color(0xFFD3C6AA),
        background: Color(0xFF232A2E),
                black: Color(0xFF7A8478),
        red: Color(0xFFE67E80),
        green: Color(0xFFA7C080),
        yellow: Color(0xFFDBBC7F),
        blue: Color(0xFF7FBBB3),
        magenta: Color(0xFFD699B6),
        cyan: Color(0xFF83C092),
        white: Color(0xFFF2EFDF),
        brightBlack: Color(0xFFA6B0A0),
        brightRed: Color(0xFFF85552),
        brightGreen: Color(0xFF8DA101),
        brightYellow: Color(0xFFDFA000),
        brightBlue: Color(0xFF3A94C5),
        brightMagenta: Color(0xFFDF69BA),
        brightCyan: Color(0xFF35A77C),
        brightWhite: Color(0xFFFFFBEF),
        searchHitBackground: Color(0xFF7FBBB3),
        searchHitBackgroundCurrent: Color(0xFFDBBC7F),
        searchHitForeground: Color(0xFF232A2E),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.githubDarkDimmed,
      label: 'GitHub Dark Dimmed',
      theme: TerminalTheme(
        cursor: Color(0xFF539BF5),
        selection: Color(0xFFADBAC7),
        foreground: Color(0xFFADBAC7),
        background: Color(0xFF22272E),
                black: Color(0xFF545D68),
        red: Color(0xFFF47067),
        green: Color(0xFF57AB5A),
        yellow: Color(0xFFC69026),
        blue: Color(0xFF539BF5),
        magenta: Color(0xFFB083F0),
        cyan: Color(0xFF39C5CF),
        white: Color(0xFF909DAB),
        brightBlack: Color(0xFF636E7B),
        brightRed: Color(0xFFFF938A),
        brightGreen: Color(0xFF6BC46D),
        brightYellow: Color(0xFFDAAA3F),
        brightBlue: Color(0xFF6CB6FF),
        brightMagenta: Color(0xFFDCBDFB),
        brightCyan: Color(0xFF56D4DD),
        brightWhite: Color(0xFFCDD9E5),
        searchHitBackground: Color(0xFF539BF5),
        searchHitBackgroundCurrent: Color(0xFFC69026),
        searchHitForeground: Color(0xFF22272E),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.gruvboxDark,
      label: 'Gruvbox Dark',
      theme: TerminalTheme(
        cursor: Color(0xFFFE8019),
        selection: Color(0xFF504945),
        foreground: Color(0xFFEBDBB2),
        background: Color(0xFF282828),
        black: Color(0xFF282828),
        red: Color(0xFFCC241D),
        green: Color(0xFF98971A),
        yellow: Color(0xFFD79921),
        blue: Color(0xFF458588),
        magenta: Color(0xFFB16286),
        cyan: Color(0xFF689D6A),
        white: Color(0xFFA89984),
        brightBlack: Color(0xFF928374),
        brightRed: Color(0xFFFB4934),
        brightGreen: Color(0xFFB8BB26),
        brightYellow: Color(0xFFFABD2F),
        brightBlue: Color(0xFF83A598),
        brightMagenta: Color(0xFFD3869B),
        brightCyan: Color(0xFF8EC07C),
        brightWhite: Color(0xFFEBDBB2),
        searchHitBackground: Color(0xFFFE8019),
        searchHitBackgroundCurrent: Color(0xFFFABD2F),
        searchHitForeground: Color(0xFF282828),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.gruvboxLight,
      label: 'Gruvbox Light',
      theme: TerminalTheme(
        cursor: Color(0xFF3C3836),
        selection: Color(0xFF3C3836),
        foreground: Color(0xFF3C3836),
        background: Color(0xFFFBF1C7),
                black: Color(0xFFFBF1C7),
        red: Color(0xFFCC241D),
        green: Color(0xFF98971A),
        yellow: Color(0xFFD79921),
        blue: Color(0xFF458588),
        magenta: Color(0xFFB16286),
        cyan: Color(0xFF689D6A),
        white: Color(0xFF7C6F64),
        brightBlack: Color(0xFF928374),
        brightRed: Color(0xFF9D0006),
        brightGreen: Color(0xFF79740E),
        brightYellow: Color(0xFFB57614),
        brightBlue: Color(0xFF076678),
        brightMagenta: Color(0xFF8F3F71),
        brightCyan: Color(0xFF427B58),
        brightWhite: Color(0xFF3C3836),
        searchHitBackground: Color(0xFF458588),
        searchHitBackgroundCurrent: Color(0xFFD79921),
        searchHitForeground: Color(0xFFFBF1C7),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.horizon,
      label: 'Horizon',
      theme: TerminalTheme(
        cursor: Color(0xFF6C6F93),
        selection: Color(0xFF6C6F93),
        foreground: Color(0xFFD5D8DA),
        background: Color(0xFF1C1E26),
                black: Color(0xFF000000),
        red: Color(0xFFE95678),
        green: Color(0xFF29D398),
        yellow: Color(0xFFFAB795),
        blue: Color(0xFF26BBD9),
        magenta: Color(0xFFEE64AC),
        cyan: Color(0xFF59E1E3),
        white: Color(0xFFE5E5E5),
        brightBlack: Color(0xFF666666),
        brightRed: Color(0xFFEC6A88),
        brightGreen: Color(0xFF3FDAA4),
        brightYellow: Color(0xFFFBC3A7),
        brightBlue: Color(0xFF3FC4DE),
        brightMagenta: Color(0xFFF075B5),
        brightCyan: Color(0xFF6BE4E6),
        brightWhite: Color(0xFFE5E5E5),
        searchHitBackground: Color(0xFF26BBD9),
        searchHitBackgroundCurrent: Color(0xFFFAB795),
        searchHitForeground: Color(0xFF1C1E26),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.kanagawaWave,
      label: 'Kanagawa Wave',
      theme: TerminalTheme(
        cursor: Color(0xFFDCD7BA),
        selection: Color(0xFFDCD7BA),
        foreground: Color(0xFFDCD7BA),
        background: Color(0xFF1F1F28),
                black: Color(0xFF090618),
        red: Color(0xFFC34043),
        green: Color(0xFF76946A),
        yellow: Color(0xFFC0A36E),
        blue: Color(0xFF7E9CD8),
        magenta: Color(0xFF957FB8),
        cyan: Color(0xFF6A9589),
        white: Color(0xFFC8C093),
        brightBlack: Color(0xFF727169),
        brightRed: Color(0xFFE82424),
        brightGreen: Color(0xFF98BB6C),
        brightYellow: Color(0xFFE6C384),
        brightBlue: Color(0xFF7FB4CA),
        brightMagenta: Color(0xFF938AA9),
        brightCyan: Color(0xFF7AA89F),
        brightWhite: Color(0xFFDCD7BA),
        searchHitBackground: Color(0xFF7E9CD8),
        searchHitBackgroundCurrent: Color(0xFFC0A36E),
        searchHitForeground: Color(0xFF1F1F28),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.material,
      label: 'Material',
      theme: TerminalTheme(
        cursor: Color(0xFF16AFCA),
        selection: Color(0xFFC2C2C2),
        foreground: Color(0xFF232322),
        background: Color(0xFFEAEAEA),
                black: Color(0xFF212121),
        red: Color(0xFFB7141F),
        green: Color(0xFF457B24),
        yellow: Color(0xFFF6981E),
        blue: Color(0xFF134EB2),
        magenta: Color(0xFF560088),
        cyan: Color(0xFF0E717C),
        white: Color(0xFFAFAFAF),
        brightBlack: Color(0xFF424242),
        brightRed: Color(0xFFE83B3F),
        brightGreen: Color(0xFF7ABA3A),
        brightYellow: Color(0xFFBFAA00),
        brightBlue: Color(0xFF54A4F3),
        brightMagenta: Color(0xFFAA4DBC),
        brightCyan: Color(0xFF26BBD1),
        brightWhite: Color(0xFFD9D9D9),
        searchHitBackground: Color(0xFF134EB2),
        searchHitBackgroundCurrent: Color(0xFFF6981E),
        searchHitForeground: Color(0xFFEAEAEA),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.monokai,
      label: 'Monokai Pro',
      theme: TerminalTheme(
        cursor: Color(0xFFFFD866),
        selection: Color(0xFF403E41),
        foreground: Color(0xFFFCFCFA),
        background: Color(0xFF2D2A2E),
        black: Color(0xFF2D2A2E),
        red: Color(0xFFFF6188),
        green: Color(0xFFA9DC76),
        yellow: Color(0xFFFFD866),
        blue: Color(0xFFFC9867),
        magenta: Color(0xFFAB9DF2),
        cyan: Color(0xFF78DCE8),
        white: Color(0xFFFCFCFA),
        brightBlack: Color(0xFF727072),
        brightRed: Color(0xFFFF6188),
        brightGreen: Color(0xFFA9DC76),
        brightYellow: Color(0xFFFFD866),
        brightBlue: Color(0xFFFC9867),
        brightMagenta: Color(0xFFAB9DF2),
        brightCyan: Color(0xFF78DCE8),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFFFFD866),
        searchHitBackgroundCurrent: Color(0xFFFF6188),
        searchHitForeground: Color(0xFF2D2A2E),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.nightOwl,
      label: 'Night Owl',
      theme: TerminalTheme(
        cursor: Color(0xFF7E57C2),
        selection: Color(0xFF5F7E97),
        foreground: Color(0xFFD6DEEB),
        background: Color(0xFF011627),
                black: Color(0xFF011627),
        red: Color(0xFFEF5350),
        green: Color(0xFF22DA6E),
        yellow: Color(0xFFADDB67),
        blue: Color(0xFF82AAFF),
        magenta: Color(0xFFC792EA),
        cyan: Color(0xFF21C7A8),
        white: Color(0xFFFFFFFF),
        brightBlack: Color(0xFF575656),
        brightRed: Color(0xFFEF5350),
        brightGreen: Color(0xFF22DA6E),
        brightYellow: Color(0xFFFFEB95),
        brightBlue: Color(0xFF82AAFF),
        brightMagenta: Color(0xFFC792EA),
        brightCyan: Color(0xFF7FDBCA),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF82AAFF),
        searchHitBackgroundCurrent: Color(0xFFADDB67),
        searchHitForeground: Color(0xFF011627),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.nord,
      label: 'Nord',
      theme: TerminalTheme(
        cursor: Color(0xFFD8DEE9),
        selection: Color(0xFF434C5E),
        foreground: Color(0xFFD8DEE9),
        background: Color(0xFF2E3440),
        black: Color(0xFF3B4252),
        red: Color(0xFFBF616A),
        green: Color(0xFFA3BE8C),
        yellow: Color(0xFFEBCB8B),
        blue: Color(0xFF81A1C1),
        magenta: Color(0xFFB48EAD),
        cyan: Color(0xFF88C0D0),
        white: Color(0xFFE5E9F0),
        brightBlack: Color(0xFF4C566A),
        brightRed: Color(0xFFD08770),
        brightGreen: Color(0xFFA3BE8C),
        brightYellow: Color(0xFFEBCB8B),
        brightBlue: Color(0xFF5E81AC),
        brightMagenta: Color(0xFFB48EAD),
        brightCyan: Color(0xFF8FBCBB),
        brightWhite: Color(0xFFECEFF4),
        searchHitBackground: Color(0xFF88C0D0),
        searchHitBackgroundCurrent: Color(0xFF81A1C1),
        searchHitForeground: Color(0xFF2E3440),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.oled,
      label: 'OLED True Black',
      theme: TerminalTheme(
        cursor: Color(0xFF00E676),
        selection: Color(0xFF263238),
        foreground: Color(0xFFECEFF1),
        background: Color(0xFF000000),
        black: Color(0xFF212121),
        red: Color(0xFFFF5252),
        green: Color(0xFF00E676),
        yellow: Color(0xFFFFD740),
        blue: Color(0xFF40C4FF),
        magenta: Color(0xFFE040FB),
        cyan: Color(0xFF18FFFF),
        white: Color(0xFFEEFFFF),
        brightBlack: Color(0xFF424242),
        brightRed: Color(0xFFFF8A80),
        brightGreen: Color(0xFFB9F6CA),
        brightYellow: Color(0xFFFFE57F),
        brightBlue: Color(0xFF80D8FF),
        brightMagenta: Color(0xFFEA80FC),
        brightCyan: Color(0xFFA7FFEB),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF00E676),
        searchHitBackgroundCurrent: Color(0xFF18FFFF),
        searchHitForeground: Color(0xFF000000),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.oneDark,
      label: 'One Dark',
      theme: TerminalTheme(
        cursor: Color(0xFF528BFF),
        selection: Color(0xFF3E4451),
        foreground: Color(0xFFABB2BF),
        background: Color(0xFF282C34),
        black: Color(0xFF1E2127),
        red: Color(0xFFE06C75),
        green: Color(0xFF98C379),
        yellow: Color(0xFFE5C07B),
        blue: Color(0xFF61AFEF),
        magenta: Color(0xFFC678DD),
        cyan: Color(0xFF56B6C2),
        white: Color(0xFFABB2BF),
        brightBlack: Color(0xFF5C6370),
        brightRed: Color(0xFFBE5046),
        brightGreen: Color(0xFF98C379),
        brightYellow: Color(0xFFD19A66),
        brightBlue: Color(0xFF61AFEF),
        brightMagenta: Color(0xFFC678DD),
        brightCyan: Color(0xFF56B6C2),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF61AFEF),
        searchHitBackgroundCurrent: Color(0xFFC678DD),
        searchHitForeground: Color(0xFF282C34),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.oneLight,
      label: 'One Light',
      theme: TerminalTheme(
        cursor: Color(0xFFBBBBBB),
        selection: Color(0xFFEDEDED),
        foreground: Color(0xFF2A2C33),
        background: Color(0xFFF9F9F9),
                black: Color(0xFF000000),
        red: Color(0xFFDE3E35),
        green: Color(0xFF3F953A),
        yellow: Color(0xFFD2B67C),
        blue: Color(0xFF2F5AF3),
        magenta: Color(0xFF950095),
        cyan: Color(0xFF3F953A),
        white: Color(0xFFBBBBBB),
        brightBlack: Color(0xFF000000),
        brightRed: Color(0xFFDE3E35),
        brightGreen: Color(0xFF3F953A),
        brightYellow: Color(0xFFD2B67C),
        brightBlue: Color(0xFF2F5AF3),
        brightMagenta: Color(0xFFA00095),
        brightCyan: Color(0xFF3F953A),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF2F5AF3),
        searchHitBackgroundCurrent: Color(0xFFD2B67C),
        searchHitForeground: Color(0xFFF9F9F9),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.rosePine,
      label: 'Rosé Pine',
      theme: TerminalTheme(
        cursor: Color(0xFFE0DEF4),
        selection: Color(0xFF403D52),
        foreground: Color(0xFFE0DEF4),
        background: Color(0xFF191724),
                black: Color(0xFF26233A),
        red: Color(0xFFEB6F92),
        green: Color(0xFF31748F),
        yellow: Color(0xFFF6C177),
        blue: Color(0xFF9CCFD8),
        magenta: Color(0xFFC4A7E7),
        cyan: Color(0xFFEBBCBA),
        white: Color(0xFFE0DEF4),
        brightBlack: Color(0xFF6E6A86),
        brightRed: Color(0xFFEB6F92),
        brightGreen: Color(0xFF31748F),
        brightYellow: Color(0xFFF6C177),
        brightBlue: Color(0xFF9CCFD8),
        brightMagenta: Color(0xFFC4A7E7),
        brightCyan: Color(0xFFEBBCBA),
        brightWhite: Color(0xFFE0DEF4),
        searchHitBackground: Color(0xFF9CCFD8),
        searchHitBackgroundCurrent: Color(0xFFF6C177),
        searchHitForeground: Color(0xFF191724),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.rosePineMoon,
      label: 'Rosé Pine Moon',
      theme: TerminalTheme(
        cursor: Color(0xFFE0DEF4),
        selection: Color(0xFF44415A),
        foreground: Color(0xFFE0DEF4),
        background: Color(0xFF232136),
                black: Color(0xFF393552),
        red: Color(0xFFEB6F92),
        green: Color(0xFF3E8FB0),
        yellow: Color(0xFFF6C177),
        blue: Color(0xFF9CCFD8),
        magenta: Color(0xFFC4A7E7),
        cyan: Color(0xFFEA9A97),
        white: Color(0xFFE0DEF4),
        brightBlack: Color(0xFF6E6A86),
        brightRed: Color(0xFFEB6F92),
        brightGreen: Color(0xFF3E8FB0),
        brightYellow: Color(0xFFF6C177),
        brightBlue: Color(0xFF9CCFD8),
        brightMagenta: Color(0xFFC4A7E7),
        brightCyan: Color(0xFFEA9A97),
        brightWhite: Color(0xFFE0DEF4),
        searchHitBackground: Color(0xFF9CCFD8),
        searchHitBackgroundCurrent: Color(0xFFF6C177),
        searchHitForeground: Color(0xFF232136),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.snazzy,
      label: 'Snazzy',
      theme: TerminalTheme(
        cursor: Color(0xFFE4E4E4),
        selection: Color(0xFF81AEC6),
        foreground: Color(0xFFEBECE6),
        background: Color(0xFF1E1F29),
                black: Color(0xFF000000),
        red: Color(0xFFFC4346),
        green: Color(0xFF50FB7C),
        yellow: Color(0xFFF0FB8C),
        blue: Color(0xFF49BAFF),
        magenta: Color(0xFFFC4CB4),
        cyan: Color(0xFF8BE9FE),
        white: Color(0xFFEDEDEC),
        brightBlack: Color(0xFF555555),
        brightRed: Color(0xFFFC4346),
        brightGreen: Color(0xFF50FB7C),
        brightYellow: Color(0xFFF0FB8C),
        brightBlue: Color(0xFF49BAFF),
        brightMagenta: Color(0xFFFC4CB4),
        brightCyan: Color(0xFF8BE9FE),
        brightWhite: Color(0xFFEDEDEC),
        searchHitBackground: Color(0xFF49BAFF),
        searchHitBackgroundCurrent: Color(0xFFF0FB8C),
        searchHitForeground: Color(0xFF1E1F29),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.solarizedDark,
      label: 'Solarized Dark',
      theme: TerminalTheme(
        cursor: Color(0xFF93A1A1),
        selection: Color(0xFF073642),
        foreground: Color(0xFF839496),
        background: Color(0xFF002B36),
        black: Color(0xFF073642),
        red: Color(0xFFDC322F),
        green: Color(0xFF859900),
        yellow: Color(0xFFB58900),
        blue: Color(0xFF268BD2),
        magenta: Color(0xFFD33682),
        cyan: Color(0xFF2AA198),
        white: Color(0xFFEEE8D5),
        brightBlack: Color(0xFF002B36),
        brightRed: Color(0xFFCB4B16),
        brightGreen: Color(0xFF586E75),
        brightYellow: Color(0xFF657B83),
        brightBlue: Color(0xFF839496),
        brightMagenta: Color(0xFF6C71C4),
        brightCyan: Color(0xFF93A1A1),
        brightWhite: Color(0xFFFDF6E3),
        searchHitBackground: Color(0xFF2AA198),
        searchHitBackgroundCurrent: Color(0xFF268BD2),
        searchHitForeground: Color(0xFF002B36),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.solarizedLight,
      label: 'Solarized Light',
      theme: TerminalTheme(
        cursor: Color(0xFF657B83),
        selection: Color(0xFFEEE8D5),
        foreground: Color(0xFF657B83),
        background: Color(0xFFFDF6E3),
                black: Color(0xFF073642),
        red: Color(0xFFDC322F),
        green: Color(0xFF859900),
        yellow: Color(0xFFB58900),
        blue: Color(0xFF268BD2),
        magenta: Color(0xFFD33682),
        cyan: Color(0xFF2AA198),
        white: Color(0xFFBBB5A2),
        brightBlack: Color(0xFF002B36),
        brightRed: Color(0xFFCB4B16),
        brightGreen: Color(0xFF586E75),
        brightYellow: Color(0xFF657B83),
        brightBlue: Color(0xFF839496),
        brightMagenta: Color(0xFF6C71C4),
        brightCyan: Color(0xFF93A1A1),
        brightWhite: Color(0xFFFDF6E3),
        searchHitBackground: Color(0xFF268BD2),
        searchHitBackgroundCurrent: Color(0xFFB58900),
        searchHitForeground: Color(0xFFFDF6E3),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.synthwave84,
      label: 'SynthWave \'84',
      theme: TerminalTheme(
        cursor: Color(0xFF19CDE6),
        selection: Color(0xFF19CDE6),
        foreground: Color(0xFFDAD9C7),
        background: Color(0xFF000000),
                black: Color(0xFF000000),
        red: Color(0xFFF6188F),
        green: Color(0xFF1EBB2B),
        yellow: Color(0xFFFDF834),
        blue: Color(0xFF2186EC),
        magenta: Color(0xFFF85A21),
        cyan: Color(0xFF12C3E2),
        white: Color(0xFFFFFFFF),
        brightBlack: Color(0xFF7F7094),
        brightRed: Color(0xFFF841A0),
        brightGreen: Color(0xFF25C141),
        brightYellow: Color(0xFFFDF454),
        brightBlue: Color(0xFF2F9DED),
        brightMagenta: Color(0xFFF97137),
        brightCyan: Color(0xFF19CDE6),
        brightWhite: Color(0xFFFFFFFF),
        searchHitBackground: Color(0xFF2186EC),
        searchHitBackgroundCurrent: Color(0xFFFDF834),
        searchHitForeground: Color(0xFF000000),
      ),
    ),
    TerminalPaletteData(
      palette: TerminalPalette.tokyoNight,
      label: 'Tokyo Night',
      theme: TerminalTheme(
        cursor: Color(0xFF7AA2F7),
        selection: Color(0xFF33467C),
        foreground: Color(0xFFC0CAF5),
        background: Color(0xFF1A1B26),
        black: Color(0xFF15161E),
        red: Color(0xFFF7768E),
        green: Color(0xFF9ECE6A),
        yellow: Color(0xFFE0AF68),
        blue: Color(0xFF7AA2F7),
        magenta: Color(0xFFBB9AF7),
        cyan: Color(0xFF7DCFFF),
        white: Color(0xFFA9B1D6),
        brightBlack: Color(0xFF414868),
        brightRed: Color(0xFFF7768E),
        brightGreen: Color(0xFF9ECE6A),
        brightYellow: Color(0xFFE0AF68),
        brightBlue: Color(0xFF7AA2F7),
        brightMagenta: Color(0xFFBB9AF7),
        brightCyan: Color(0xFF7DCFFF),
        brightWhite: Color(0xFFC0CAF5),
        searchHitBackground: Color(0xFF7AA2F7),
        searchHitBackgroundCurrent: Color(0xFFBB9AF7),
        searchHitForeground: Color(0xFF1A1B26),
      ),
    ),
];