/// Terminal color schemes selectable in Settings.
///
/// Values are persisted by `name` — append only, never rename or reorder.
enum TerminalPalette {
  dark,
  oled,
  catppuccin,
  nord,
  dracula,
  solarizedDark,
  tokyoNight,
  gruvboxDark,
  oneDark,
  monokai,
  cyberpunk,
  catppuccinMocha,
  catppuccinLatte,
  rosePine,
  rosePineMoon,
  kanagawaWave,
  everforestDark,
  ayuMirage,
  material,
  doomOne,
  nightOwl,
  synthwave84,
  horizon,
  snazzy,
  githubDarkDimmed,
  solarizedLight,
  gruvboxLight,
  oneLight,
  nocturne,
  githubLight,
  tokyoNightDay,
  rosePineDawn,
  ayuLight,
  everforestLight,
  kanagawaLotus,
  nordLight,
  lightOwl,
  monokaiProLight,
  flexokiLight,
  xcodeLight,

  /// Not a scheme of its own: follows the app palette and brightness to the
  /// scheme paired with them. Resolve it through
  /// `AppSettingsModel.resolvedTerminalPalette` before looking up colours.
  matchApp,
}
